#!/bin/sh

# build — Cold build for Atelier

# Atelier (https://github.com/melusina-org/cl-atelier)
# This file is part of Atelier.
#
# Copyright © 2017–2023 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${buildsystem:="org.melusina.atelier"}
: ${testsystem:="org.melusina.atelier/testsuite"}

build_sbcl()
{
    sbcl --noinform --disable-debugger "$@"
}

# build_atelier [-v]
#  Cold build of ${buildsystem} and ${testsystem}
#
# Every compiler message is emitted on standard output or standard error.
# `:force t` recompiles every component of the named system regardless of
# the state of the ASDF output cache.

build_atelier()
{
    local verbose
    verbose=false
    while getopts 'v' OPTION; do
	case "${OPTION}" in
	    v)	verbose=true;;
	esac
    done

    set --

    if [ "${verbose}" = 'true' ]; then
	set -- "$@" --eval "(setf *compile-verbose* t
                    	      *compile-print* t
                              *load-verbose* t
                              *load-print* t)"
    fi
    
    cd "${TOPLEVELDIR}" && build_sbcl "$@"\
	 --eval "(unless (ql:where-is-system \"${buildsystem}\")
                   (pushnew #p\"${TOPLEVELDIR}\" ql:*local-project-directories*)
                   (ql:register-local-projects))"\
	 --eval "(asdf:load-system \"${buildsystem}\" :force t :verbose t)"\
	 --eval "(asdf:load-system \"${testsystem}\" :force t :verbose t)"\
	 --eval '(uiop:quit 0)'
}

build_atelier "$@"

# End of file `build'
