#!/bin/sh

# publish — Publish artefact

# Atelier (https://github.com/melusina-org/cl-atelier)
# This file is part of Atelier.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${buildsystem:="org.melusina.atelier"}
: ${subrdir:=${TOPLEVELDIR}/subr}
: ${dockerdir:="${TOPLEVELDIR}/docker"}

. "${subrdir}/stdlib.sh"
. "${subrdir}/cid.sh"

publish_docker_image()
(
    local tag tty

    first ()
    {
	sed -n '1{p;q;}'
    }

    if [ -z "$(docker_registry)" ]; then
	printf 'publish: %s: No docker registry is set, so we do not publish this image.\n'\
	       "$1"
	return
    fi

    tag=$(docker_tags "$1" | first )
    docker push "${tag}"
)

publish_artefact()
{
    local artefact
    for artefact in "$@"; do
	printf 'publish: artefact: %s\n' "${artefact}"
        case "${artefact}" in
            docker/*)
                publish_docker_image "${artefact#docker/}"
                ;;
            *)
                failwith '%s: Nothing is known about this kind of artefact.' "${artefact#/*}"
                ;;
        esac
	if [ $? -gt 0 ]; then
	    failwith 'publish: artefact: %s: There were some errors' "${artefact}"
	fi
    done
}

publish_main()
{
    if [ $# -eq 0 ]; then
        set --\
	    'docker/linux'
    fi
    publish_artefact "$@"
}

publish_main "$@"

# End of file `publish'
