#!/bin/sh

# testsuite — Run test suite

# Atelier (https://github.com/melusina-org/cl-atelier)
# This file is part of Atelier.
#
# Copyright © 2017–2026 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${testsuitesystem:="org.melusina.atelier/test"}
: ${testsuitepackage:=${testsuitesystem#'org.melusina.'}}
: ${testsuiteclean:='no'}
: ${testsuitelisp:='sbcl'}

: ${subrdir:=${TOPLEVELDIR}/subr}

. "${subrdir}/stdlib.sh"


testsuite_run()
{
    local test_entry_point

    if [ $# -eq 0 ]; then
	set -- 'run-all-tests'
    fi

    cl -Q 'confidence:quit' -L "${testsuitesystem}" "${testsuitepackage}:$1"
    
}

testsuite_main()
{
    local OPTIND OPTION OPTARG
    OPTIND=1

    while getopts 'CL:' OPTION; do
	case "${OPTION}" in
	    C)	testsuiteclean='yes';;
	    L)	testsuitelisp="${OPTARG}";;
	esac
    done

    shift $((OPTIND - 1))

    if [ "${testsuiteclean}" = 'yes' ]; then
	(cd "${TOPLEVELDIR}" && development/clean)
    fi

    testsuite_run "$@"
}

testsuite_main "$@"

# End of file `testsuite'
