# action.yml

# Atelier (https://github.com/melusina-org/cl-atelier)
# This file is part of Atelier.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

name: 'Makedoc'
description: 'Build documentation for Lisp projects'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - /opt/local/bin/describe
