#!/bin/sh

#### lint — Linter for ${PROJECT_NAME}

# ${PROJECT_NAME} (${HOMEPAGE})
# This file is part of ${PROJECT_NAME}.
#
# Copyright © ${COPYRIGHT_YEAR} ${COPYRIGHT_HOLDER}
# All rights reserved.

# ${LICENSE_HEADER}

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}

lint_sbcl()
{
    sbcl --noinform --disable-debugger "$@"
}

lint_main()
{
    lint_sbcl --load "${TOPLEVELDIR}/libexec/lisp/setup.lisp"\
	      --eval '(org.melusina.atelier:lint #p"src" #p"testsuite")'
}

lint_main "$@"

### End of file `lint'
