#!/bin/sh

#### testsuite — Testsuite for ${PROJECT_NAME}

# ${PROJECT_NAME} (${HOMEPAGE})
# This file is part of ${PROJECT_NAME}.
#
# Copyright © ${COPYRIGHT_YEAR} ${COPYRIGHT_HOLDER}
# All rights reserved.

# ${LICENSE_HEADER}

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${testsuitesystem:="${LISP_TEST_SYSTEM_NAME}"}
: ${testsuiteclean:='no'}
: ${testsuitelisp:='sbcl'}

testsuite_lisp()
{
    case "${testsuitelisp}" in
	sbcl)
	    sbcl --noinform --disable-debugger "$@"
	    ;;
	ccl|ccl64)
	    ccl64 "$@"
	    ;;
    esac
}

testsuite_run()
{
    if [ $# -eq 0 ]; then
	set -- 'run-all-tests'
    fi
    testsuite_lisp\
	--eval "(ql:quickload \"${testsuitesystem}\" :silent t)"\
	--eval "(${testsuitesystem}:$1)"
}

testsuite_main()
{
    local OPTIND OPTION OPTARG
    OPTIND=1

    while getopts 'CL:' OPTION; do
	case "${OPTION}" in
	    C)	testsuiteclean='yes';;
	    L)	testsuitelisp="${OPTARG}";;
	esac
    done

    shift $((OPTIND - 1))

    if [ "${testsuiteclean}" = 'yes' ]; then
	(cd "${TOPLEVELDIR}" && development/clean)
    fi
    
    testsuite_run "$@"
}

testsuite_main "$@"

### End of file `testsuite'
