;;;; tool.lisp — Tool class, resource-tool mixin, registries

;;;; Atelier (https://github.com/melusina-org/cl-atelier)
;;;; This file is part of Atelier.
;;;;
;;;; Copyright © 2017–2026 Michaël Le Barbier
;;;; All rights reserved.

;;;; SPDX-License-Identifier: MIT

(in-package #:atelier/mcp)

;;; Tool hierarchy. Concrete tool classes are generated per
;;; define-tool form. Each tool class carries its metadata on reader
;;; methods, not slots (see references/define-tool-macro.md for the
;;; rationale).

(defclass tool ()
  ()
  (:documentation
   "Abstract base class for MCP tools. Concrete subclasses are
    generated by DEFINE-TOOL. Tool metadata (name, description,
    input-schema) lives on per-class reader methods, not slots.
    Never instantiated directly."))

(defclass resource-tool ()
  ()
  (:documentation
   "Mixin marking a tool definition as also exposed as an MCP resource.
    Concrete classes combine TOOL and RESOURCE-TOOL. Resource metadata
    (uri template, name, mime-type) lives on per-class reader methods."))

;;; Per-tool metadata accessors. The default methods exist only to make
;;; the symbols defined; DEFINE-TOOL emits class-specialised methods.

(defgeneric tool-name (tool)
  (:documentation "Return the MCP tool name string for TOOL."))

(defgeneric tool-description (tool)
  (:documentation "Return the human-readable description for TOOL."))

(defgeneric tool-input-schema (tool)
  (:documentation "Return the JSON Schema hash-table for TOOL's arguments."))

(defgeneric resource-uri-template (tool)
  (:documentation
   "Return the URI template string for TOOL when it is a resource-tool,
    NIL otherwise."))

(defmethod resource-uri-template ((tool tool))
  nil)

(defgeneric resource-name (tool)
  (:documentation "Return the MCP resource name string for TOOL."))

(defgeneric resource-mime-type (tool)
  (:documentation
   "Return the declared MIME type string for TOOL as a JSON Schema
    mimeType field value. NIL for tool-only definitions."))

(defmethod resource-mime-type ((tool tool))
  nil)

(defgeneric handle-tool-call (tool arguments)
  (:documentation
   "Execute TOOL with parsed ARGUMENTS (alist of string keys to values).
    Return the handler body's return value. The dispatcher converts
    the result to the appropriate MCP response envelope."))

;;; Registries. Three hash-tables keyed by tool name or URI template.

(defvar *tool-registry* (make-hash-table :test 'equal)
  "Hash-table of tool name -> TOOL instance. Keys are strings.
   Every tool created by DEFINE-TOOL without (:tool nil) is registered
   here. Resource-only definitions are absent.")

(defvar *concrete-resource-registry* (make-hash-table :test 'equal)
  "Hash-table of concrete URI -> RESOURCE-TOOL instance. Keys are
   strings without {placeholder} segments.")

(defvar *template-resource-registry* (make-hash-table :test 'equal)
  "Hash-table of URI template string -> RESOURCE-TOOL instance. Keys
   are template strings that contain at least one {placeholder}.")

;;; Registration entry point. DEFINE-TOOL expands to a call to this
;;; function. The presence of a RESOURCE-TOOL mixin selects resource
;;; registration; the template is inspected with URI-TEMPLATE-STATIC-P
;;; to choose between the concrete and template registries.

(defun register-tool (instance &key (register-as-tool t))
  "Install INSTANCE into the appropriate registries.
   REGISTER-AS-TOOL defaults to T; pass NIL for resource-only
   definitions (those emitted from (:tool nil) in DEFINE-TOOL)."
  (when register-as-tool
    (setf (gethash (tool-name instance) *tool-registry*) instance))
  (when (typep instance 'resource-tool)
    (%register-resource instance))
  instance)

(defun %register-resource (instance)
  "Insert INSTANCE into the concrete or template resource registry
   based on its URI template shape."
  (let ((template (resource-uri-template instance)))
    (if (uri-template-static-p template)
        (setf (gethash template *concrete-resource-registry*) instance)
        (setf (gethash template *template-resource-registry*) instance))))

;;; Read-only accessors for the registries. Used by dispatcher methods
;;; that build tools/list, resources/list, and resources/templates/list
;;; responses.

(defun list-tools ()
  "Return a fresh list of all registered tools."
  (loop :for tool :being :the :hash-values :of *tool-registry*
        :collect tool))

(defun list-concrete-resources ()
  "Return a fresh list of all registered concrete (static-URI)
   resource tools."
  (loop :for tool :being :the :hash-values :of *concrete-resource-registry*
        :collect tool))

(defun list-template-resources ()
  "Return a fresh list of all registered URI-templated resource tools."
  (loop :for tool :being :the :hash-values :of *template-resource-registry*
        :collect tool))

(defun find-tool-by-name (name)
  "Return the tool instance registered under NAME, or NIL."
  (gethash name *tool-registry*))

(defun find-concrete-resource-by-uri (uri)
  "Return the concrete resource tool registered under URI, or NIL."
  (gethash uri *concrete-resource-registry*))

(defun match-resource-uri (uri)
  "Find the resource tool that serves URI.
   Returns (VALUES TOOL BINDINGS). On miss, returns (VALUES NIL NIL).
   Lookup order: concrete registry first, then template registry
   walked in definition order."
  (let ((concrete (find-concrete-resource-by-uri uri)))
    (if concrete
        (values concrete nil)
        (%match-templates uri))))

(defun %match-templates (uri)
  "Walk *TEMPLATE-RESOURCE-REGISTRY* looking for a template that
   matches URI. Returns the same shape as MATCH-RESOURCE-URI."
  (loop :for template :being :the :hash-keys :of *template-resource-registry*
          :using (:hash-value tool)
        :do (multiple-value-bind (bindings matched-p)
                (match-uri-against-template uri template)
              (when matched-p
                (return-from %match-templates (values tool bindings))))
        :finally (return (values nil nil))))

;;;; End of file `tool.lisp'
