#!/bin/sh

# linux — Test Docker Image for Personalised Linux system

# Atelier (https://github.com/melusina-org/cl-atelier)
# This file is part of Atelier.
#
# Copyright © 2017–2023 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${PACKAGE:='local'}
set -ex
test -x /usr/bin/vi
test -x /usr/bin/sbcl
test -x /usr/bin/bsdtar
test -f "/opt/${PACKAGE}/share/bsdowl/bps.uses.mk"
id atelier

# End of file `linux'
