# action.yaml — Definition of the build-validate-publish action

# Atelier (https://github.com/melusina-org/cl-atelier)
# This file is part of Atelier.
#
# Copyright © 2017–2022 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

name: 'Build, validate and publish'
description: 'Build, validate and publish an artefact'
inputs:
  registry:
    description: 'The registry to push artefact to'
    required: false
    default: 'ghcr.io'
  artefact:
    description: 'The artefact to build'
    required: true
  description:
    description: 'The description of the artefact to build.'
    required: true
  license:
    description: 'The licence of the artefact to build.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3

    - name: 'Describe build environment'
      run: development/describe

    - name: 'Log in to the Artefact registry'
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Build Artefact'
      run: development/build {{ inputs.artefact }}

    - name: 'Validate Artefact'
      run: development/testimage {{ inputs.artefact }}

    - name: 'Publish Artefact'
      run: development/publish {{ inputs.artefact }}

# End of file `action.yaml'
