name: 'Continuous Integration'
on:
  - workflow_dispatch
  - push
jobs:
  continuous-integration:
    name: 'Lisp Continuous Integration'
    uses: melusina-org/reusable/.github/workflows/lisp-continuous-integration.yaml@v1
