name: Delivery

on:
  - workflow_dispatch

jobs:
  delivery:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v1
    - uses: foretspaisibles/cl-atelier/actions/makedoc@github
