name: 'Create and publish Linux Docker image'

on:
  - workflow_dispatch
  - push

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Describe build environment'
        run: development/describe

      - name: 'Log in to the Container registry'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Docker image'
        run: development/build docker/linux

      - name: 'Test Docker image'
        run: development/testimage docker/linux

      - name: 'Publish Docker image'
        run: development/publish docker/linux
